-- db_minyak_migration.sql
-- Target: Supabase / PostgreSQL
-- Purpose: Schema migration for the oil collection app.

create extension if not exists pgcrypto;

do $$ begin
  create type status_akun_type as enum ('aktif', 'nonaktif', 'petugas', 'admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type status_petugas_type as enum ('aktif', 'nonaktif');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type status_verifikasi_type as enum ('pending', 'approved', 'rejected');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type status_hadiah_type as enum ('aktif', 'nonaktif');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type status_penukaran_type as enum ('pending', 'approved', 'rejected', 'done');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type jenis_reward_type as enum ('setoran', 'bonus', 'penyesuaian');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type jenis_mutasi_type as enum ('credit', 'debit');
exception when duplicate_object then null;
end $$;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = current_timestamp;
  return new;
end;
$$;

create table if not exists cabang (
  cabang_id bigint generated by default as identity primary key,
  kode_cabang varchar(30) not null unique,
  nama_cabang varchar(120) not null,
  alamat text,
  aktif boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_cabang_updated_at on cabang;
create trigger trg_cabang_updated_at
before update on cabang
for each row execute function set_updated_at();

create table if not exists users (
  user_id bigint generated by default as identity primary key,
  cabang_id bigint references cabang(cabang_id) on delete set null,
  nama varchar(120) not null,
  email varchar(190) not null unique,
  password varchar(255) not null,
  status_akun status_akun_type not null default 'aktif',
  poin integer not null default 0,
  tanggal_daftar timestamptz not null default current_timestamp,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_users_updated_at on users;
create trigger trg_users_updated_at
before update on users
for each row execute function set_updated_at();

create table if not exists petugas (
  petugas_id bigint generated by default as identity primary key,
  user_id bigint not null unique references users(user_id) on delete cascade,
  cabang_id bigint references cabang(cabang_id) on delete set null,
  jabatan varchar(100),
  status_petugas status_petugas_type not null default 'aktif',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_petugas_updated_at on petugas;
create trigger trg_petugas_updated_at
before update on petugas
for each row execute function set_updated_at();

create table if not exists reward_rule (
  rule_id bigint generated by default as identity primary key,
  nama_rule varchar(120) not null,
  minimal_liter numeric(10,2) not null default 0,
  poin_per_liter integer not null default 10,
  bonus_poin integer not null default 0,
  aktif boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_reward_rule_updated_at on reward_rule;
create trigger trg_reward_rule_updated_at
before update on reward_rule
for each row execute function set_updated_at();

create table if not exists setoran_minyak (
  setoran_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  petugas_id bigint references petugas(petugas_id) on delete set null,
  cabang_id bigint references cabang(cabang_id) on delete set null,
  rule_id bigint references reward_rule(rule_id) on delete set null,
  tanggal_setor timestamptz not null default current_timestamp,
  jumlah_liter numeric(10,2) not null,
  poin_didapat integer not null default 0,
  status_verifikasi status_verifikasi_type not null default 'pending',
  verified_at timestamptz,
  verified_by bigint references users(user_id) on delete set null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_setoran_minyak_updated_at on setoran_minyak;
create trigger trg_setoran_minyak_updated_at
before update on setoran_minyak
for each row execute function set_updated_at();

create index if not exists idx_setoran_user on setoran_minyak (user_id);
create index if not exists idx_setoran_petugas on setoran_minyak (petugas_id);
create index if not exists idx_setoran_cabang on setoran_minyak (cabang_id);
create index if not exists idx_setoran_status on setoran_minyak (status_verifikasi);
create index if not exists idx_setoran_tanggal on setoran_minyak (tanggal_setor);

create table if not exists saldo_poin (
  saldo_id bigint generated by default as identity primary key,
  user_id bigint not null unique references users(user_id) on delete cascade,
  total_poin integer not null default 0,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_saldo_poin_updated_at on saldo_poin;
create trigger trg_saldo_poin_updated_at
before update on saldo_poin
for each row execute function set_updated_at();

create table if not exists hadiah (
  hadiah_id bigint generated by default as identity primary key,
  nama_hadiah varchar(140) not null,
  deskripsi text,
  poin_dibutuhkan integer not null,
  stok integer not null default 0,
  status_hadiah status_hadiah_type not null default 'aktif',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

drop trigger if exists trg_hadiah_updated_at on hadiah;
create trigger trg_hadiah_updated_at
before update on hadiah
for each row execute function set_updated_at();

create table if not exists penukaran_reward (
  penukaran_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  hadiah_id bigint not null references hadiah(hadiah_id) on delete restrict,
  jumlah integer not null default 1,
  total_poin_dipakai integer not null default 0,
  status_penukaran status_penukaran_type not null default 'pending',
  requested_at timestamptz not null default current_timestamp,
  processed_at timestamptz,
  processed_by bigint references users(user_id) on delete set null,
  catatan text
);

create index if not exists idx_penukaran_user on penukaran_reward (user_id);
create index if not exists idx_penukaran_hadiah on penukaran_reward (hadiah_id);
create index if not exists idx_penukaran_status on penukaran_reward (status_penukaran);

create table if not exists reward_transaksi (
  reward_transaksi_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  rule_id bigint references reward_rule(rule_id) on delete set null,
  setoran_id bigint references setoran_minyak(setoran_id) on delete set null,
  jenis_reward jenis_reward_type not null default 'setoran',
  poin integer not null,
  deskripsi varchar(255),
  created_at timestamptz not null default current_timestamp
);

create index if not exists idx_reward_user on reward_transaksi (user_id);
create index if not exists idx_reward_rule on reward_transaksi (rule_id);
create index if not exists idx_reward_setoran on reward_transaksi (setoran_id);

create table if not exists mutasi_point (
  mutasi_id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  jenis_mutasi jenis_mutasi_type not null,
  referensi_tabel varchar(64),
  referensi_id bigint,
  poin integer not null,
  poin_sebelum integer not null default 0,
  poin_sesudah integer not null default 0,
  keterangan varchar(255),
  created_at timestamptz not null default current_timestamp
);

create index if not exists idx_mutasi_user on mutasi_point (user_id);
create index if not exists idx_mutasi_created on mutasi_point (created_at);

insert into reward_rule (nama_rule, minimal_liter, poin_per_liter, bonus_poin, aktif)
select 'Default Rule', 0, 10, 0, true
where not exists (
  select 1 from reward_rule where nama_rule = 'Default Rule'
);

insert into cabang (kode_cabang, nama_cabang, alamat)
select 'CBG-UTAMA', 'Cabang Utama', 'Belum diatur'
where not exists (
  select 1 from cabang where kode_cabang = 'CBG-UTAMA'
);

insert into users (nama, email, password, status_akun, poin)
select 'Petugas Admin', 'admin@setorminyak.local', md5('admin123'), 'petugas', 0
where not exists (
  select 1 from users where email = 'admin@setorminyak.local'
);

insert into petugas (user_id, jabatan, status_petugas)
select u.user_id, 'Petugas Lapangan', 'aktif'
from users u
left join petugas p on p.user_id = u.user_id
where u.email = 'admin@setorminyak.local'
  and p.petugas_id is null;

insert into saldo_poin (user_id, total_poin)
select u.user_id, u.poin
from users u
left join saldo_poin sp on sp.user_id = u.user_id
where sp.user_id is null;

do $$
begin
  if to_regclass('public."user"') is not null then
    insert into users (user_id, nama, email, password, status_akun, poin, tanggal_daftar)
    select u.user_id, u.nama, u.email, u.password, coalesce(u.status_akun, 'aktif')::status_akun_type, coalesce(u.poin, 0), coalesce(u.tanggal_daftar, current_timestamp)
    from public."user" u
    left join users nu on nu.user_id = u.user_id
    where nu.user_id is null;
  end if;
end $$;